### ISSUE TITLE
ROT stack is wrong after DUP

### ISSUE THREAD

**Issue by Stanley00** [boricj/numworks-rpn#25] opened 2020-05-04 06:42 UTC
## Step to reproduce
1 EXE
2 EXE
3 EXE
EXE
( <= now it just rotates 3 numbers while stack has 4 numbers

## Environment
Omega version 1.19.2 on Android phone

**Comment by boricj** [comment] 2020-05-04 08:16
ROT is behaving like its counterpart in HP's RPN calculators. What you're describing sounds like "n ROLL" in RPL, which is not implemented, but you can copy any number on the stack to the input field by selecting it and pressing OK/EXE.

This app is meant to emulate HP's traditional RPN calculators. I'll close this issue since ROT behaves as designed, feel free to re-open it if you actually want "n ROLL" implemented.

**Closed as completed by boricj** 2020-05-04 08:16 UTC

**Comment by Stanley00** [comment] 2020-05-04 09:37
Oh, you're right. I was just mis-understand behavior of ROT then. This issue could be closed. Thank you.
